name: 'HTTP request to IAP-protected app'
description: 'Action for making HTTP request to IAP-protected app'
author: 'Edgar Hernandez'
inputs:
  url:
    required: true
    description: 'Url to send request'
  target-audience:
    required: true
    description: 'Target audience'
  service_account_key:
    required: true
    description: 'Service account'
  method:
    required: false
    default: GET
    description: 'HTTP method'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: phone-call